name: benchmark

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - dev 

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get install -y csvkit
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - uses: actions/checkout@v4
      - name: Tests
        run: |
          go test -v -bench=. -race -count=1 -coverprofile=coverage.txt