name: unit 

on:
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - uses: actions/checkout@v4
      - name: Tests
        run: |
          make test 
      - name: Upload Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.txt
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}